server.port: 8060

spring:
  application:
    name: gollum-authentication
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz972e3u722f8ojsweo.mysql.rds.aliyuncs.com:3306/gollum_dev?useUnicode=true&characterEncoding=UTF-8
    username: gollum_admin
    password: gollum@123
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    serialization:
      indent_output: true   #JSON格式化


management.endpoints.web.exposure.include: '*'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sapce.entities

logging:
  level:
    root: debug

jwt.header: Authorization
jwt.secret: mySecret
jwt.expiration: 604800
jwt.tokenHead: Bearer


#服务端版本
version: 1.0
environment: local